source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SIStoryboardI18N_Example', :exclusive => true do
  pod "SIStoryboardI18N", :path => "../"
end

target 'SIStoryboardI18N_Tests', :exclusive => true do
  pod "SIStoryboardI18N", :path => "../"

  pod 'FBSnapshotTestCase'
end
